# Generated by Django 3.2.9 on 2022-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_firstname', models.CharField(max_length=30)),
                ('host_lastname', models.CharField(max_length=30)),
                ('host_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
