# Generated by Django 3.2.9 on 2022-12-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221220_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_email',
        ),
    ]
