# Generated by Django 3.2.9 on 2022-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_host_host_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='host_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
