# Generated by Django 3.2.9 on 2022-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221220_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
