# Generated by Django 3.2.9 on 2022-12-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_host_host_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='event_address',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='city',
            new_name='event_city',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.DateTimeField(null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='host_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='host_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host',
            field=models.CharField(max_length=30),
        ),
    ]
