# Generated by Django 3.2.9 on 2022-12-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221220_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.URLField(default=''),
        ),
    ]
