# Generated by Django 3.2.9 on 2022-12-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_event_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_event',
            field=models.ManyToManyField(to='main.Event'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_id',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
