# Generated by Django 3.2.9 on 2022-12-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20221220_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='host_firstname',
            new_name='host_first_name',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='host_lastname',
            new_name='host_last_name',
        ),
    ]
