# Generated by Django 3.2.9 on 2022-12-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_event_event_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=50)),
                ('drink_is_alcoholic', models.BooleanField(default=False)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('drink_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food_is_vege', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_responsible_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.host'),
        ),
    ]
