# Generated by Django 3.2.9 on 2022-12-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20221220_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_place',
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_address', models.CharField(max_length=30)),
                ('place_evene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('place_host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.host')),
            ],
        ),
    ]
