# Generated by Django 3.2.9 on 2022-12-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20221221_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_evene',
            new_name='place_event',
        ),
    ]
