# Generated by Django 3.2.9 on 2022-12-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_place_evene_place_place_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
