# Generated by Django 3.2.9 on 2022-12-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20221221_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
