# Generated by Django 3.2.9 on 2022-12-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20221221_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_drink',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_food',
        ),
    ]
