# Generated by Django 3.2.9 on 2022-12-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20221221_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.drink'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.food'),
        ),
    ]
