# Generated by Django 3.2.9 on 2022-12-21 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20221221_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Start Time'),
        ),
    ]
